lucidi
csunibo/laboratorio-sicurezza-informatica pull request #1
Opened 2023-02-22 12:39 UTC by specialfish9

2023-02-22 14:24 UTC, foxyseta requested changes
Ciao! Forse dovresti controllare meglio la regexp prove

2023-02-22 14:39 UTC, lucat1 commented
Si si ma gli ho anche detto che puo' cambiarle se hanno piu' senso in un altro modo per questo corso

2023-02-22 15:56 UTC, foxyseta commented
> Si si ma gli ho anche detto che puo' cambiarle se hanno piu' senso in un altro modo per questo corso

Ottimo!
@specialfish9 nel caso non ti avesse già spiegato @lucat1 ecco la regexp se vuoi cambiarla:

https://github.com/csunibo/laboratorio-sicurezza-informatica/blob/76939df185e94bc34ec404c16b358bfa85e1e439/.github/workflows/check.yml#L56

Ed ecco la documentazione:

https://github.com/csunibo/laboratorio-sicurezza-informatica/blob/76939df185e94bc34ec404c16b358bfa85e1e439/README.md?plain=1#L29

P.S. ho unfiformato il README alle altre repo sulla tua branch, quindi se riesci ricordati di pullare prima del commit.

2023-02-24 12:15 UTC, lucat1 approved these changes

2023-02-24 12:15 UTC, merged